- name: Установка инструментов
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker.io
      - docker-compose

- name: Настройка Docker для пользователя
  block:
    - name: Создание группы docker
      group:
        name: docker
        state: present

    - name: Добавление пользователя в группу docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
  when: ansible_user is defined

- name: Создание необходимых директорий
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/monitoring
    - /opt/monitoring/volumes
    - /opt/monitoring/grafana/dashboards
    - /opt/monitoring/grafana/provisioning/datasources
    - /opt/monitoring/grafana/provisioning/dashboards
    - /opt/monitoring/grafana/dashboards
    - /opt/monitoring/loki
    - /opt/monitoring/promtail

- name: Копирование конфигурационных файлов
  copy:
    src: "files/{{ item.src }}"
    dest: "/opt/monitoring/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'docker-compose.yml', dest: 'docker-compose.yml' }
    - { src: 'prometheus/prometheus.yml', dest: 'prometheus.yml' }
    - { src: 'prometheus/web.config.yml', dest: 'web.config.yml' }
    - { src: 'grafana/provisioning/datasources/prometheus.yml', dest: 'grafana/provisioning/datasources/prometheus.yml' }
    - { src: 'grafana/provisioning/datasources/loki.yml', dest: 'grafana/provisioning/datasources/loki.yml' }
    - { src: 'grafana/dashboards/system_monitoring.json', dest: 'grafana/dashboards/system_monitoring.json' }
    - { src: 'grafana/provisioning/dashboards/dashboard.yml', dest: 'grafana/provisioning/dashboards/dashboard.yml' }
    - { src: 'loki/config.yml', dest: 'loki/config.yml' }
    - { src: 'promtail/config.yml', dest: 'promtail/config.yml' }

- name: Запуск сборки крнтейнеров и мониторинга системы
  shell: |
    cd /opt/monitoring
    docker-compose up -d
  args:
    chdir: /opt/monitoring