apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
    jsonData:
      timeInterval: "10s"
      queryTimeout: "30s"
      httpMethod: GET
      exemplarTraceIdDestinations: []
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.2.1
      cacheLevel: 'None'
    version: 1
    editable: true
    isDefault: true 