---
- name: Установка инструментов
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker.io
      - docker-compose

- name: Настройка Docker для пользователя
  block:
    - name: Создание группы docker
      group:
        name: docker
        state: present

    - name: Добавление пользователя в группу docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
  when: ansible_user is defined

- name: Создание директории для RabbitMQ
  file:
    path: "{{ item   }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/rabbitmq
    - /opt/rabbitmq/volumes

- name: Копирование конфигурационных файлов
  copy:
    src: "files/{{ item.src }}"
    dest: "/opt/rabbitmq/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'docker-compose.yml', dest: 'docker-compose.yml' }

- name: Развертывание RabbitMQ
  shell: |
    cd /opt/rabbitmq
    docker-compose up -d
  args:
    chdir: /opt/rabbitmq