server:
  http_listen_port: 3100

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

ruler:
  enable: true
  storage:
    boltdb_shipper:
      directory: /loki/ruler
  rule_path: /loki/rules


limits_config:
  ingestion_rate_mb: 5
  ingestion_burst_size_mb: 10
