# auth_enabled: false

# server:
#   http_listen_port: 3100

# common:
#   path_prefix: /loki
#   storage:
#     filesystem:
#       chunks_directory: /loki/data/chunks
#       rules_directory: /loki/data/rules
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory
      
# schema_config:
#   configs:
#     - from: 2024-01-01
#       store: tsdb
#       object_store: filesystem
#       schema: v12
#       index:
#         period: 24h
#         prefix: index_

# limits_config:
